apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r5drlsjn3-go 
  janus-idp.io/tekton: r5drlsjn3-go
  backstage.io/kubernetes-id: r5drlsjn3-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r5drlsjn3-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml